### ISSUE TITLE
automatic semicolon insertion

### ISSUE THREAD

**Issue by hoosierEE** [rtfeldman/elm-fullscreen#2]
This line gave me some weird ASI feelings:

https://github.com/rtfeldman/elm-fullscreen/blob/master/src/Native/Fullscreen.js#L21

And reading [the spec](http://ecma-international.org/ecma-262/5.1/#sec-7.9.1) affirmed those feelings.  Suggested remedies:
1. put all the `||` things in a var, and return that var.
2. put all the `||` things on the same line as `return`

**Comment by rtfeldman** [comment]
Thanks! Nice catch.

**Comment by hoosierEE** [comment]
Cheers!  Hope to give this a test-drive soon, thanks for authoring.  :smile_cat:
